### ISSUE TITLE
Set this up as a recurring task?

### ISSUE THREAD

**Issue by paf31** [hdgarrood/pursuit-check-missing#1]

**Comment by hdgarrood** [comment]
I'm just a bit wary of reaching a point where people just tag things on GitHub and expect them to appear on pursuit; it would increase the ops burden and I'm not sure the effect would be worth it. I'm actually working towards `pulp release` now which should pretty much remove all the friction that stops packages from reaching pursuit currently, hopefully rendering this obsolete (although that's probably a bit optimistic).

**Comment by paf31** [comment]
Well I think you'd still have to upload once, but after that, new releases would be taken care of. I see what you mean though. And `pulp release` will be amazing to have.

**Comment by hdgarrood** [comment]
Ah yes, of course you are right about needing to upload once.
